### ISSUE TITLE
🔍 Solution Overview

### ISSUE THREAD

**Issue by kitsonk** [denoland/meet-me#2]
# User Journeys

1. **Acquisition Journey**

    As a potential user of cal, I want to be able to view information about the solution to determine if I want to sign up for the product.

2. **Signup Journey**

    As an intended user of cal, I want to be able to signup for cal, using my Google Account for identification and authentication and linking my cal account to my Google Calendar. I also want to select some default configuration details about how I want cal to operate.

3. **Cal Configuration Journey**

    As an authenticated user, I want in interface to be able to configure my meeting slots as well as well as configure other options associated with my account.

4. **Cal Visitor Journey**

    As an unauthenticated user/visitor to a specific users page, I want to be presented with the available meetings slots for the user so I can book a meeting with them.

6. **Cancellation Journey**

    As an authenticated user, I want to be able to un-enroll in cal.

# Infrastructure

- CI/CD (GitHub Actions)
- Frontend Tooling (Aleph.js)
- Business Logic/Middleware/Client API (Deploy Services)
- Persistance (Supabase)

# Initial Work Break Down

- **Infrastructure**
  - Scaffold out CI/CD
  - Setup architectural decision records

- **Frontend**
  - Mocks/Designs for Landing, Sign-up, Configuration, Visitor/Booking pages
  - Scaffold out Aleph.js for "pages" (Landing, Sign-up, Configuration, Visitor/Booking)

- **Middleware**
  - Design domain model (event storm?)
  - Design process flow for sign-up
  - Design process flow for configuration
  - Design process flow for booking creation and change
  - Design and build mock APIs based on domain model and flows

- **Integrations**
  - Investigate and Detail OAuth integration with Google
  - Investigate and Detail Google Calendar Permissions and APIs
  - Investigate and Detail notifications via e-mail

- **Backend**
  - Investigate and Detail supabase integration
  - Design data model based on domain model
  - Implement data store design

**Comment by kt3k** [comment]
Closing as first pass has been done now
