### ISSUE TITLE
Server rendering error during onboarding

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/meet-me#67]
> The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.

https://reactjs.org/docs/error-decoder.html/?invariant=419

![image](https://user-images.githubusercontent.com/7062160/176548711-178a55c2-ad52-46ca-bf0a-369f52d1ddb3.png)

After reloading the page, onboarding worked.

**Comment by MarkTiedemann** [comment]
Seems to happen on every page load actually (e.g. https://meet-me.deno.dev/mark). Using Firefox 102.0 on Windows.

**Comment by kt3k** [comment]
@MarkTiedemann Thanks for trying Meet Me.

The error is most likely being caused by recently update of aleph #66. We are working on this. Thanks for your report.

**Comment by kt3k** [comment]
We updated the framework. Does this issue persist?

**Comment by MarkTiedemann** [comment]
No, the issue is gone. Thanks!
