### ISSUE TITLE
Google Blocks OAuth by default

### ISSUE THREAD

**Issue by John8790909** [denoland/meet-me#71]
<img width="1001" alt="Screen Shot 2022-07-07 at 12 16 01 PM" src="https://user-images.githubusercontent.com/79988159/177822009-71c000cc-2696-46d9-9b85-ba2d93f09e09.png">

**Comment by kt3k** [comment]
Please follow the instruction here at the moment https://github.com/denoland/meet-me#google-trust-and-safety-verification

We're trying to get this app approved by Google Trust and Safety team to avoid that screen. It will need another days (or weeks).

**Comment by John8790909** [comment]
Thanks for the advice @kt3k

**Comment by StrangeGirlMurph** [comment]
Can I do anything when I just don't get that "Advanced" button to circumvent this?
